// frontend/src/views/Logs.vue
<template>
  <div class="logs-page">
    <!-- 日志筛选 -->
    <el-card class="filter-card">
      <el-form :inline="true" :model="filters">
        <el-form-item label="日志类型">
          <el-select v-model="filters.log_type" placeholder="全部" clearable>
            <el-option label="访问日志" :value="1" />
            <el-option label="切换日志" :value="2" />
            <el-option label="错误日志" :value="3" />
            <el-option label="测试日志" :value="4" />
          </el-select>
        </el-form-item>
        
        <el-form-item label="模型">
          <el-select v-model="filters.model_id" placeholder="全部" clearable>
            <el-option 
              v-for="m in modelList" 
              :key="m.id" 
              :label="m.model_name" 
              :value="m.id" 
            />
          </el-select>
        </el-form-item>
        
        <el-form-item label="状态">
          <el-select v-model="filters.status" placeholder="全部" clearable>
            <el-option label="成功" :value="1" />
            <el-option label="失败" :value="0" />
          </el-select>
        </el-form-item>
        
        <el-form-item label="时间范围">
          <el-date-picker
            v-model="filters.date_range"
            type="datetimerange"
            range-separator="至"
            start-placeholder="开始时间"
            end-placeholder="结束时间"
            :shortcuts="dateShortcuts"
          />
        </el-form-item>
        
        <el-form-item>
          <el-button type="primary" @click="handleSearch">
            <el-icon><Search /></el-icon>
            搜索
          </el-button>
          <el-button @click="handleReset">
            <el-icon><Refresh /></el-icon>
            重置
          </el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="table-card">
      <template #header>
        <div class="card-header">
          <div class="header-left">
            <el-radio-group v-model="activeTab" size="small">
              <el-radio-button :label="null">全部</el-radio-button>
              <el-radio-button :label="1">访问日志</el-radio-button>
              <el-radio-button :label="2">切换日志</el-radio-button>
              <el-radio-button :label="3">错误日志</el-radio-button>
            </el-radio-group>
          </div>
          <div class="header-actions">
            <el-button @click="handleExport">
              <el-icon><Download /></el-icon>
              导出
            </el-button>
            <el-button type="danger" @click="handleClear" :loading="clearing">
              <el-icon><Delete /></el-icon>
              清空
            </el-button>
          </div>
        </div>
      </template>

      <el-table :data="tableData" v-loading="loading" stripe @row-click="handleRowClick">
        <el-table-column prop="id" label="ID" width="80" />
        
        <el-table-column label="时间" width="180">
          <template #default="{ row }">
            {{ formatTime(row.create_time) }}
          </template>
        </el-table-column>
        
        <el-table-column label="类型" width="100">
          <template #default="{ row }">
            <el-tag :type="getLogTypeTag(row.log_type)" size="small">
              {{ getLogTypeName(row.log_type) }}
            </el-tag>
          </template>
        </el-table-column>
        
        <el-table-column label="模型" width="150">
          <template #default="{ row }">
            {{ getModelName(row.model_id) }}
          </template>
        </el-table-column>
        
        <el-table-column label="状态" width="80">
          <template #default="{ row }">
            <el-icon :color="row.status ? '#67C23A' : '#F56C6C'">
              <CircleCheck v-if="row.status" />
              <CircleClose v-else />
            </el-icon>
          </template>
        </el-table-column>
        
        <el-table-column label="内容" min-width="300">
          <template #default="{ row }">
            <el-button 
              v-if="row.log_content && row.log_content.length > 100"
              type="primary" 
              link
              @click.stop="handleViewContent(row)"
            >
              查看详情
            </el-button>
            <span v-else>{{ row.log_content }}</span>
          </template>
        </el-table-column>
      </el-table>

      <div class="pagination-container">
        <el-pagination
          v-model:current-page="pagination.page"
          v-model:page-size="pagination.size"
          :page-sizes="[20, 50, 100, 200]"
          :total="pagination.total"
          layout="total, sizes, prev, pager, next, jumper"
          @size-change="handleSizeChange"
          @current-change="handlePageChange"
        />
      </div>
    </el-card>

    <!-- 日志详情对话框 -->
    <el-dialog
      v-model="detailVisible"
      title="日志详情"
      width="700px"
    >
      <el-descriptions :column="2" border v-if="currentLog">
        <el-descriptions-item label="日志ID" :span="2">
          {{ currentLog.id }}
        </el-descriptions-item>
        <el-descriptions-item label="日志类型">
          <el-tag :type="getLogTypeTag(currentLog.log_type)">
            {{ getLogTypeName(currentLog.log_type) }}
          </el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="状态">
          <el-icon :color="currentLog.status ? '#67C23A' : '#F56C6C'">
            <CircleCheck v-if="currentLog.status" />
            <CircleClose v-else />
          </el-icon>
        </el-descriptions-item>
        <el-descriptions-item label="创建时间">
          {{ formatTime(currentLog.create_time) }}
        </el-descriptions-item>
        <el-descriptions-item label="关联模型">
          {{ getModelName(currentLog.model_id) }}
        </el-descriptions-item>
        <el-descriptions-item label="日志内容" :span="2">
          <el-input
            type="textarea"
            :rows="4"
            :value="currentLog.log_content"
            readonly
            class="log-content"
          />
        </el-descriptions-item>
        <el-descriptions-item label="请求内容" :span="2">
          <el-input
            type="textarea"
            :rows="8"
            :value="formatJson(currentLog.request_content)"
            readonly
            class="log-content"
            v-if="currentLog.request_content"
          />
          <span v-else>-</span>
        </el-descriptions-item>
        <el-descriptions-item label="响应内容" :span="2">
          <el-input
            type="textarea"
            :rows="8"
            :value="formatJson(currentLog.response_content)"
            readonly
            class="log-content"
            v-if="currentLog.response_content"
          />
          <span v-else>-</span>
        </el-descriptions-item>
        <el-descriptions-item label="错误信息" :span="2" v-if="currentLog.error_message">
          <el-input
            type="textarea"
            :rows="4"
            :value="currentLog.error_message"
            readonly
            class="log-content"
          />
        </el-descriptions-item>
      </el-descriptions>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search, Refresh, Download, Delete, CircleCheck, CircleClose } from '@element-plus/icons-vue'
import { logApi, modelApi } from '@/api'
import dayjs from 'dayjs'

const loading = ref(false)
const clearing = ref(false)
const tableData = ref([])
const modelList = ref([])
const detailVisible = ref(false)
const currentLog = ref(null)
const activeTab = ref(null)

const filters = reactive({
  log_type: null,
  model_id: null,
  status: null,
  date_range: null
})

const pagination = reactive({
  page: 1,
  size: 50,
  total: 0
})

const dateShortcuts = [
  { text: '今天', value: () => [dayjs().startOf('day'), dayjs().endOf('day')] },
  { text: '最近3天', value: () => [dayjs().subtract(3, 'day'), dayjs().endOf('day')] },
  { text: '最近7天', value: () => [dayjs().subtract(7, 'day'), dayjs().endOf('day')] },
  { text: '最近30天', value: () => [dayjs().subtract(30, 'day'), dayjs().endOf('day')] }
]

watch(activeTab, (val) => {
  filters.log_type = val
  pagination.page = 1
  fetchData()
})

const formatTime = (time) => {
  return time ? dayjs(time).format('YYYY-MM-DD HH:mm:ss') : '-'
}

const formatJson = (str) => {
  if (!str) return ''
  try {
    const obj = typeof str === 'string' ? JSON.parse(str) : str
    return JSON.stringify(obj, null, 2)
  } catch {
    return str
  }
}

const getLogTypeName = (type) => {
  const map = { 1: '访问日志', 2: '切换日志', 3: '错误日志', 4: '测试日志' }
  return map[type] || '未知'
}

const getLogTypeTag = (type) => {
  const map = { 1: '', 2: 'success', 3: 'danger', 4: 'info' }
  return map[type] || 'info'
}

const getModelName = (modelId) => {
  if (!modelId) return '-'
  const model = modelList.value.find(m => m.id === modelId)
  return model ? `${model.vendor}/${model.model_name}` : `ID: ${modelId}`
}

const fetchData = async () => {
  loading.value = true
  try {
    const params = {
      page: pagination.page,
      size: pagination.size,
      log_type: filters.log_type,
      model_id: filters.model_id,
      status: filters.status
    }
    
    if (filters.date_range) {
      params.start_time = filters.date_range[0].toISOString()
      params.end_time = filters.date_range[1].toISOString()
    }
    
    const res = await logApi.list(params)
    
    // 后端返回: { code, msg, data: [...], total: n }
    tableData.value = res.data || []
    pagination.total = res.total || 0
  } catch (error) {
    ElMessage.error('获取日志失败')
  } finally {
    loading.value = false
  }
}

const fetchModels = async () => {
  try {
    const res = await modelApi.list()
    modelList.value = res.data || []
  } catch (error) {
    console.error('获取模型列表失败')
  }
}

const handleSearch = () => {
  pagination.page = 1
  fetchData()
}

const handleReset = () => {
  filters.log_type = null
  filters.model_id = null
  filters.status = null
  filters.date_range = null
  activeTab.value = null
  handleSearch()
}

const handleSizeChange = () => {
  pagination.page = 1
  fetchData()
}

const handlePageChange = () => {
  fetchData()
}

const handleRowClick = (row) => {
  // 可选：点击行显示详情
}

const handleViewContent = (row) => {
  currentLog.value = row
  detailVisible.value = true
}

const handleExport = async () => {
  try {
    await logApi.export(filters)
    ElMessage.success('导出成功')
  } catch (error) {
    ElMessage.error('导出失败')
  }
}

const handleClear = async () => {
  try {
    await ElMessageBox.confirm(
      '确定要清空所有日志吗？此操作不可恢复。',
      '清空确认',
      { type: 'warning' }
    )
    clearing.value = true
    await logApi.clear(filters.log_type)
    ElMessage.success('日志已清空')
    fetchData()
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('清空失败')
    }
  } finally {
    clearing.value = false
  }
}

onMounted(() => {
  fetchData()
  fetchModels()
})
</script>

<style lang="scss" scoped>
.logs-page {
  .filter-card {
    margin-bottom: 20px;
  }
  
  .table-card {
    .card-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      
      .header-actions {
        display: flex;
        gap: 12px;
      }
    }
    
    .pagination-container {
      margin-top: 20px;
      display: flex;
      justify-content: flex-end;
    }
  }
  
  .log-content {
    font-family: 'Monaco', 'Menlo', monospace;
    font-size: 12px;
  }
}
</style>

// frontend-react/src/pages/Logs.jsx
import React, { useState, useEffect } from 'react';
import { Card, Table, Tag, Button, Space, Select, DatePicker, Input, Radio, Drawer, message, Popconfirm } from 'antd';
import { SearchOutlined, DeleteOutlined, DownloadOutlined, ReloadOutlined, EyeOutlined } from '@ant-design/icons';
import { logApi, modelApi } from '../services/api';
import dayjs from 'dayjs';

const { RangePicker } = DatePicker;

const Logs = () => {
  const [tableData, setTableData] = useState([]);
  const [modelList, setModelList] = useState([]);
  const [loading, setLoading] = useState(false);
  const [pagination, setPagination] = useState({ current: 1, pageSize: 20, total: 0 });
  const [filters, setFilters] = useState({});
  const [detailVisible, setDetailVisible] = useState(false);
  const [currentLog, setCurrentLog] = useState(null);

  useEffect(() => {
    fetchData();
    fetchModels();
  }, [pagination.current, filters]);

  const fetchData = async () => {
    setLoading(true);
    try {
      const params = {
        page: pagination.current,
        size: pagination.pageSize,
        ...filters
      };
      const response = await logApi.list(params);
      if (response.code === 200) {
        setTableData(response.data || []);
        setPagination({ ...pagination, total: response.total || response.data?.length || 0 });
      }
    } catch (error) {
      message.error('获取日志失败');
    } finally {
      setLoading(false);
    }
  };

  const fetchModels = async () => {
    try {
      const response = await modelApi.list();
      if (response.code === 200) {
        setModelList(response.data || []);
      }
    } catch (error) {
      console.error('获取模型列表失败:', error);
    }
  };

  const handleSearch = () => {
    setPagination({ ...pagination, current: 1 });
    fetchData();
  };

  const handleReset = () => {
    setFilters({});
    setPagination({ ...pagination, current: 1 });
    setTimeout(fetchData, 0);
  };

  const handleClear = async (logType) => {
    try {
      await logApi.clear(logType);
      message.success('日志已清空');
      fetchData();
    } catch (error) {
      message.error('清空失败');
    }
  };

  const handleExport = async () => {
    try {
      const response = await logApi.export(filters);
      const blob = new Blob([response.data], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'logs.csv';
      link.click();
      message.success('导出成功');
    } catch (error) {
      message.error('导出失败');
    }
  };

  const handleViewDetail = (record) => {
    setCurrentLog(record);
    setDetailVisible(true);
  };

  const getLogTypeName = (type) => {
    const map = { 1: '访问日志', 2: '切换日志', 3: '错误日志', 4: '测试日志' };
    return map[type] || '未知';
  };

  const getLogTypeColor = (type) => {
    const map = { 1: 'blue', 2: 'green', 3: 'red', 4: 'orange' };
    return map[type] || 'default';
  };

  const formatJson = (str) => {
    if (!str) return '-';
    try {
      const obj = typeof str === 'string' ? JSON.parse(str) : str;
      return JSON.stringify(obj, null, 2);
    } catch {
      return str;
    }
  };

  const columns = [
    {
      title: 'ID',
      dataIndex: 'id',
      width: 80
    },
    {
      title: '时间',
      dataIndex: 'create_time',
      width: 180
    },
    {
      title: '类型',
      dataIndex: 'log_type',
      render: (type) => <Tag color={getLogTypeColor(type)}>{getLogTypeName(type)}</Tag>
    },
    {
      title: '模型',
      dataIndex: 'model_id',
      render: (id) => {
        const model = modelList.find(m => m.id === id);
        return model ? `${model.vendor}/${model.model_name}` : `ID: ${id}`;
      }
    },
    {
      title: '状态',
      dataIndex: 'status',
      render: (status) => (
        status === 1 ?
          <Tag color="success">成功</Tag> :
          <Tag color="error">失败</Tag>
      )
    },
    {
      title: '内容',
      dataIndex: 'log_content',
      ellipsis: true
    },
    {
      title: '操作',
      render: (_, record) => (
        <Space>
          <Button type="text" icon={<EyeOutlined />} onClick={() => handleViewDetail(record)}>
            详情
          </Button>
        </Space>
      )
    }
  ];

  return (
    <div>
      <Card className="filter-card">
        <Space wrap>
          <Select
            placeholder="日志类型"
            allowClear
            style={{ width: 130 }}
            options={[
              { label: '访问日志', value: 1 },
              { label: '切换日志', value: 2 },
              { label: '错误日志', value: 3 },
              { label: '测试日志', value: 4 }
            ]}
            value={filters.log_type}
            onChange={(value) => setFilters({ ...filters, log_type: value })}
          />
          <Select
            placeholder="模型"
            allowClear
            style={{ width: 180 }}
            options={modelList.map(m => ({
              label: `${m.vendor}/${m.model_name}`,
              value: m.id
            }))}
            value={filters.model_id}
            onChange={(value) => setFilters({ ...filters, model_id: value })}
          />
          <Select
            placeholder="状态"
            allowClear
            style={{ width: 100 }}
            options={[
              { label: '成功', value: 1 },
              { label: '失败', value: 0 }
            ]}
            value={filters.status}
            onChange={(value) => setFilters({ ...filters, status: value })}
          />
          <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
            搜索
          </Button>
          <Button onClick={handleReset}>重置</Button>
        </Space>
      </Card>

      <Card
        title="日志列表"
        extra={
          <Space>
            <Button icon={<DownloadOutlined />} onClick={handleExport}>
              导出
            </Button>
            <Popconfirm
              title="确定清空所有日志?"
              onConfirm={() => handleClear()}
            >
              <Button danger icon={<DeleteOutlined />}>
                清空
              </Button>
            </Popconfirm>
            <Button icon={<ReloadOutlined />} onClick={fetchData}>
              刷新
            </Button>
          </Space>
        }
        className="table-card"
      >
        <Table
          dataSource={tableData}
          columns={columns}
          rowKey="id"
          loading={loading}
          pagination={{
            current: pagination.current,
            pageSize: pagination.pageSize,
            total: pagination.total,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total) => `共 ${total} 条`
          }}
          onChange={(paginationInfo) => {
            setPagination({
              ...pagination,
              current: paginationInfo.current,
              pageSize: paginationInfo.pageSize
            });
          }}
        />
      </Card>

      <Drawer
        title="日志详情"
        open={detailVisible}
        onClose={() => setDetailVisible(false)}
        width={600}
      >
        {currentLog && (
          <div>
            <div className="detail-row">
              <span className="label">日志ID:</span>
              <span className="content">{currentLog.id}</span>
            </div>
            <div className="detail-row">
              <span className="label">时间:</span>
              <span className="content">{currentLog.create_time}</span>
            </div>
            <div className="detail-row">
              <span className="label">类型:</span>
              <span className="content">
                <Tag color={getLogTypeColor(currentLog.log_type)}>
                  {getLogTypeName(currentLog.log_type)}
                </Tag>
              </span>
            </div>
            <div className="detail-row">
              <span className="label">状态:</span>
              <span className="content">
                {currentLog.status === 1 ?
                  <Tag color="success">成功</Tag> :
                  <Tag color="error">失败</Tag>
                }
              </span>
            </div>
            <div className="detail-row">
              <span className="label">模型ID:</span>
              <span className="content">{currentLog.model_id}</span>
            </div>
            <div className="detail-row">
              <span className="label">请求模型:</span>
              <span className="content">{currentLog.request_model || '-'}</span>
            </div>
            <div className="detail-row">
              <span className="label">实际模型:</span>
              <span className="content">{currentLog.actual_model || '-'}</span>
            </div>
            <div className="detail-row">
              <span className="label">内容:</span>
              <pre style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
                {currentLog.log_content}
              </pre>
            </div>
            <div className="detail-row">
              <span className="label">请求内容:</span>
              <pre style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-all', maxHeight: '300px', overflow: 'auto', background: '#f5f5f5', padding: '8px' }}>
                {formatJson(currentLog.request_content)}
              </pre>
            </div>
            <div className="detail-row">
              <span className="label">响应内容:</span>
              <pre style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-all', maxHeight: '300px', overflow: 'auto', background: '#f5f5f5', padding: '8px' }}>
                {formatJson(currentLog.response_content)}
              </pre>
            </div>
            {currentLog.error_message && (
              <div className="detail-row">
                <span className="label">错误信息:</span>
                <pre style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-all', maxHeight: '200px', overflow: 'auto', background: '#fff1f0', padding: '8px', color: '#ff4d4f' }}>
                  {currentLog.error_message}
                </pre>
              </div>
            )}
          </div>
        )}
      </Drawer>
    </div>
  );
};

export default Logs;
