// frontend/src/views/ModelConfig.vue
<template>
  <div class="model-config">
    <el-card class="filter-card">
      <el-form :inline="true" :model="filters">
        <el-form-item label="厂商">
          <el-select v-model="filters.vendor" placeholder="全部" clearable>
            <el-option 
              v-for="v in vendorOptions" 
              :key="v.value" 
              :label="v.label" 
              :value="v.value" 
            />
          </el-select>
        </el-form-item>
        <el-form-item label="状态">
          <el-select v-model="filters.status" placeholder="全部" clearable>
            <el-option label="启用" :value="1" />
            <el-option label="禁用" :value="0" />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleSearch">搜索</el-button>
          <el-button @click="handleReset">重置</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="table-card">
      <template #header>
        <div class="card-header">
          <span>模型配置列表</span>
          <div class="header-actions">
            <el-button type="primary" @click="handleAdd">
              <el-icon><Plus /></el-icon>
              添加模型
            </el-button>
            <el-button @click="handleBatchTest">
              <el-icon><Connection /></el-icon>
              批量测试
            </el-button>
          </div>
        </div>
      </template>

      <el-table :data="tableData" v-loading="loading" stripe>
        <el-table-column prop="vendor" label="厂商" width="120">
          <template #default="{ row }">
            <el-tag>{{ getVendorName(row.vendor) }}</el-tag>
          </template>
        </el-table-column>
        
        <el-table-column prop="model_name" label="模型名称" min-width="150" />
        
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <el-switch
              v-model="row.status"
              :active-value="1"
              :inactive-value="0"
              @change="handleStatusChange(row)"
            />
          </template>
        </el-table-column>
        
        <el-table-column label="连通性" width="100">
          <template #default="{ row }">
            <el-icon :color="row.connect_status ? '#67C23A' : '#F56C6C'">
              <CircleCheck v-if="row.connect_status" />
              <CircleClose v-else />
            </el-icon>
          </template>
        </el-table-column>
        
        <el-table-column label="额度" width="120">
          <template #default="{ row }">
            <el-tag :type="getQuotaTagType(row.quota_status)" size="small">
              {{ getQuotaStatus(row.quota_status) }}
            </el-tag>
          </template>
        </el-table-column>
        
        <el-table-column prop="priority" label="优先级" width="80" />
        
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button-group>
              <el-tooltip content="测试连通">
                <el-button size="small" @click="handleTest(row)">
                  <el-icon><Connection /></el-icon>
                </el-button>
              </el-tooltip>
              <el-tooltip content="编辑">
                <el-button size="small" @click="handleEdit(row)">
                  <el-icon><Edit /></el-icon>
                </el-button>
              </el-tooltip>
              <el-tooltip content="删除">
                <el-button size="small" type="danger" @click="handleDelete(row)">
                  <el-icon><Delete /></el-icon>
                </el-button>
              </el-tooltip>
            </el-button-group>
          </template>
        </el-table-column>
      </el-table>

      <div class="pagination-container">
        <el-pagination
          v-model:current-page="pagination.page"
          v-model:page-size="pagination.size"
          :page-sizes="[10, 20, 50, 100]"
          :total="pagination.total"
          layout="total, sizes, prev, pager, next, jumper"
          @size-change="handleSizeChange"
          @current-change="handlePageChange"
        />
      </div>
    </el-card>

    <!-- 添加/编辑对话框 -->
    <el-dialog
      v-model="dialogVisible"
      :title="dialogType === 'add' ? '添加模型' : '编辑模型'"
      width="600px"
      :close-on-click-modal="false"
    >
      <el-form ref="formRef" :model="formData" :rules="formRules" label-width="100px">
        <el-form-item label="厂商" prop="vendor">
          <el-select v-model="formData.vendor" placeholder="选择厂商" @change="handleVendorChange">
            <el-option 
              v-for="v in vendorOptions" 
              :key="v.value" 
              :label="v.label" 
              :value="v.value" 
            />
          </el-select>
        </el-form-item>
        
        <el-form-item label="模型名称" prop="model_name">
          <el-select 
            v-model="formData.model_name" 
            placeholder="选择模型"
            :disabled="dialogType === 'edit'"
          >
            <el-option 
              v-for="m in getModelOptions(formData.vendor)" 
              :key="m" 
              :label="m" 
              :value="m" 
            />
          </el-select>
        </el-form-item>
        
        <el-form-item label="API Key" prop="api_key">
          <el-input 
            v-model="formData.api_key" 
            type="password"
            show-password
            placeholder="请输入API Key"
          />
        </el-form-item>
        
        <el-form-item label="API地址" prop="api_base">
          <el-input v-model="formData.api_base" placeholder="API基础地址" />
        </el-form-item>
        
        <el-form-item label="温度" prop="temperature">
          <el-slider 
            v-model="formData.temperature" 
            :min="0" 
            :max="2" 
            :step="0.1"
            :marks="{0: '0', 1: '1', 2: '2'}"
          />
        </el-form-item>
        
        <el-form-item label="最大Token" prop="max_tokens">
          <el-input-number v-model="formData.max_tokens" :min="1" :max="32768" />
        </el-form-item>
        
        <el-form-item label="优先级" prop="priority">
          <el-input-number v-model="formData.priority" :min="1" :max="999" />
          <span class="form-tip">数字越小优先级越高</span>
        </el-form-item>
      </el-form>
      
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleSave" :loading="saving">
          测试并保存
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Connection, Edit, Delete, CircleCheck, CircleClose } from '@element-plus/icons-vue'
import { modelApi } from '@/api'

const loading = ref(false)
const saving = ref(false)
const tableData = ref([])
const dialogVisible = ref(false)
const dialogType = ref('add')
const formRef = ref(null)

const filters = reactive({
  vendor: null,
  status: null
})

const pagination = reactive({
  page: 1,
  size: 10,
  total: 0
})

const formData = reactive({
  id: null,
  vendor: '',
  model_name: '',
  api_key: '',
  api_base: '',
  temperature: 0.7,
  max_tokens: 2048,
  priority: 100
})

const formRules = {
  vendor: [{ required: true, message: '请选择厂商', trigger: 'change' }],
  model_name: [{ required: true, message: '请选择模型', trigger: 'change' }],
  api_key: [{ required: true, message: '请输入API Key', trigger: 'blur' }]
}

// 厂商选项
const vendorOptions = [
  { value: 'openai', label: 'OpenAI' },
  { value: 'qwen', label: '通义千问' },
  { value: 'zhipu', label: '智谱清言' },
  { value: 'spark', label: '讯飞星火' },
  { value: 'doubao', label: '字节豆包' },
  { value: 'claude', label: 'Claude' },
  { value: 'gemini', label: 'Google Gemini' },
  { value: 'mistral', label: 'Mistral' },
  { value: 'groq', label: 'Groq (Llama3)' }
]

// 模型配置模板
const modelTemplates = {
  openai: ['gpt-3.5-turbo', 'gpt-4o', 'gpt-4o-mini'],
  qwen: ['qwen-turbo', 'qwen-plus', 'qwen-max'],
  zhipu: ['glm-3-turbo', 'glm-4', 'glm-4v'],
  spark: ['spark-v3.1', 'spark-v3.5'],
  doubao: ['Doubao-pro-32k'],
  claude: ['claude-sonnet-4-20250514', 'claude-haiku-3-20250514'],
  gemini: ['gemini-pro', 'gemini-pro-vision'],
  mistral: ['mistral-tiny', 'mistral-small', 'mistral-medium'],
  groq: ['llama3-8b-8192', 'llama3-70b-8192', 'mixtral-8x7b-32768']
}

const getVendorName = (vendor) => {
  return vendorOptions.find(v => v.value === vendor)?.label || vendor
}

const getModelOptions = (vendor) => {
  return modelTemplates[vendor] || []
}

const getQuotaStatus = (status) => {
  const map = { 0: '已耗尽', 1: '即将耗尽', 2: '充足' }
  return map[status] || '未知'
}

const getQuotaTagType = (status) => {
  const map = { 0: 'danger', 1: 'warning', 2: 'success' }
  return map[status] || 'info'
}

const fetchData = async () => {
  loading.value = true
  try {
    const res = await modelApi.list({
      vendor: filters.vendor,
      status: filters.status
    })
    // 后端返回: { code, msg, data: [...] }
    tableData.value = res.data || []
    pagination.total = tableData.value.length
  } catch (error) {
    ElMessage.error('获取模型列表失败')
  } finally {
    loading.value = false
  }
}

const handleSearch = () => {
  pagination.page = 1
  fetchData()
}

const handleReset = () => {
  filters.vendor = null
  filters.status = null
  handleSearch()
}

const handleSizeChange = () => {
  pagination.page = 1
  fetchData()
}

const handlePageChange = () => {
  fetchData()
}

const handleAdd = () => {
  dialogType.value = 'add'
  Object.assign(formData, {
    id: null,
    vendor: '',
    model_name: '',
    api_key: '',
    api_base: '',
    temperature: 0.7,
    max_tokens: 2048,
    priority: 100
  })
  dialogVisible.value = true
}

const handleEdit = (row) => {
  dialogType.value = 'edit'
  Object.assign(formData, {
    id: row.id,
    vendor: row.vendor,
    model_name: row.model_name,
    api_key: '',
    api_base: row.api_base || '',
    temperature: row.params?.temperature || 0.7,
    max_tokens: row.params?.max_tokens || 2048,
    priority: row.priority
  })
  dialogVisible.value = true
}

const handleDelete = async (row) => {
  try {
    await ElMessageBox.confirm(
      `确定要删除模型 "${row.model_name}" 吗？`,
      '删除确认',
      { type: 'warning' }
    )
    await modelApi.delete(row.id)
    ElMessage.success('删除成功')
    fetchData()
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('删除失败')
    }
  }
}

const handleTest = async (row) => {
  try {
    await modelApi.test(row.id)
    ElMessage.success('连通测试成功')
    fetchData()
  } catch (error) {
    ElMessage.error('连通测试失败')
  }
}

const handleBatchTest = async () => {
  const enabledModels = tableData.value.filter(m => m.status === 1)
  if (enabledModels.length === 0) {
    ElMessage.warning('没有启用的模型')
    return
  }
  
  for (const model of enabledModels) {
    try {
      await modelApi.test(model.id)
    } catch (error) {
      console.error(`模型 ${model.model_name} 测试失败`)
    }
  }
  ElMessage.success('批量测试完成')
  fetchData()
}

const handleStatusChange = async (row) => {
  try {
    if (row.status === 1) {
      await modelApi.enable(row.id)
    } else {
      await modelApi.disable(row.id)
    }
    ElMessage.success(row.status ? '已启用' : '已禁用')
  } catch (error) {
    row.status = row.status ? 0 : 1
    ElMessage.error('状态更新失败')
  }
}

const handleVendorChange = () => {
  formData.model_name = ''
  // 设置默认API地址
  const baseUrls = {
    openai: 'https://api.openai.com',
    qwen: 'https://dashscope.aliyuncs.com',
    zhipu: 'https://open.bigmodel.cn',
    claude: 'https://api.anthropic.com',
    gemini: 'https://generativelanguage.googleapis.com'
  }
  formData.api_base = baseUrls[formData.vendor] || ''
}

const handleSave = async () => {
  try {
    await formRef.value.validate()
    saving.value = true
    
    // 先测试连通性
    const testRes = await modelApi.test({ 
      vendor: formData.vendor,
      model_name: formData.model_name,
      api_key: formData.api_key,
      api_base: formData.api_base
    })
    
    // 保存配置
    const saveData = {
      vendor: formData.vendor,
      model_name: formData.model_name,
      api_key: formData.api_key,
      api_base: formData.api_base,
      params: {
        temperature: formData.temperature,
        max_tokens: formData.max_tokens
      },
      priority: formData.priority
    }
    
    if (dialogType.value === 'add') {
      await modelApi.add(saveData)
    } else {
      await modelApi.update(formData.id, saveData)
    }
    
    ElMessage.success(dialogType.value === 'add' ? '添加成功' : '更新成功')
    dialogVisible.value = false
    fetchData()
  } catch (error) {
    if (error !== false) {
      ElMessage.error(error.msg || '操作失败')
    }
  } finally {
    saving.value = false
  }
}

onMounted(() => {
  fetchData()
})
</script>

<style lang="scss" scoped>
.model-config {
  .filter-card {
    margin-bottom: 20px;
  }
  
  .card-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    
    .header-actions {
      display: flex;
      gap: 12px;
    }
  }
  
  .pagination-container {
    margin-top: 20px;
    display: flex;
    justify-content: flex-end;
  }
  
  .form-tip {
    margin-left: 8px;
    font-size: 12px;
    color: #909399;
  }
}
</style>

// frontend-react/src/pages/ModelConfig.jsx
import React, { useState, useEffect } from 'react';
import {
  Table, Card, Button, Tag, Space, Input, Select, Modal, Form,
  InputNumber, Switch, message, Popconfirm, Tooltip
} from 'antd';
import {
  PlusOutlined, ApiOutlined, EditOutlined,
  DeleteOutlined, SearchOutlined, CheckCircleFilled,
  CloseCircleFilled
} from '@ant-design/icons';
import { modelApi } from '../services/api';

// 厂商默认配置（API Base 和模型列表）
const VENDOR_CONFIGS = {
  openai: {
    name: 'OpenAI',
    apiBase: 'https://api.openai.com/v1',
    models: ['gpt-3.5-turbo', 'gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-4'],
    needApiKey: true
  },
  qwen: {
    name: '通义千问',
    apiBase: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    models: ['qwen-turbo', 'qwen-plus', 'qwen-max', 'qwen2-72b-instruct'],
    needApiKey: true
  },
  zhipu: {
    name: '智谱清言',
    apiBase: 'https://api.bigmodel.cn/api/llm/v3.5',
    models: ['glm-3-turbo', 'glm-4', 'glm-4v', 'glm-4-plus'],
    needApiKey: true
  },
  spark: {
    name: '讯飞星火',
    apiBase: 'https://spark-api.xf-yun.com/v3.1/chat',
    models: ['spark-v3.1', 'spark-v3.5'],
    needApiKey: true
  },
  doubao: {
    name: '字节豆包',
    apiBase: 'https://ark.cn-beijing.volces.com/api/v3',
    models: ['Doubao-pro-32k', 'Doubao-pro-128k'],
    needApiKey: true
  },
  claude: {
    name: 'Claude',
    apiBase: 'https://api.anthropic.com/v1',
    models: ['claude-sonnet-4-20250514', 'claude-haiku-3-20250514', 'claude-opus-4-20250514'],
    needApiKey: true
  },
  gemini: {
    name: 'Google Gemini',
    apiBase: 'https://generativelanguage.googleapis.com/v1beta',
    models: ['gemini-1.5-pro', 'gemini-1.5-flash', 'gemini-pro'],
    needApiKey: true
  },
  mistral: {
    name: 'Mistral AI',
    apiBase: 'https://api.mistral.ai/v1',
    models: ['mistral-tiny', 'mistral-small', 'mistral-medium', 'mistral-large', 'open-mistral-7b'],
    needApiKey: true
  },
  groq: {
    name: 'Groq (Llama3)',
    apiBase: 'https://api.groq.com/openai/v1',
    models: ['llama3-8b-8192', 'llama3-70b-8192', 'mixtral-8x7b-32768'],
    needApiKey: true
  },
  // 本地模型
  ollama: {
    name: 'Ollama (本地)',
    apiBase: 'http://localhost:11434/v1',
    models: ['llama3', 'llama3.1', 'qwen2', 'mistral', 'codellama', 'phi3'],
    needApiKey: false
  },
  localai: {
    name: 'LocalAI (本地)',
    apiBase: 'http://localhost:8080/v1',
    models: ['llama-2-7b', 'mistral-7b', 'codellama-7b', 'gpt-4all'],
    needApiKey: false
  },
  lmstudio: {
    name: 'LM Studio (本地)',
    apiBase: 'http://localhost:1234/v1',
    models: ['llama-3-8b', 'mistral-7b', 'neural-chat', 'starcoder'],
    needApiKey: false
  },
  vllm: {
    name: 'vLLM (本地)',
    apiBase: 'http://localhost:8000/v1',
    models: ['llama-2-7b', 'llama-2-13b', 'llama-2-70b', 'qwen-14b'],
    needApiKey: false
  }
};

// 厂商选项
const vendorOptions = Object.entries(VENDOR_CONFIGS).map(([value, config]) => ({
  value,
  label: config.name,
  needApiKey: config.needApiKey
}));

const ModelConfig = () => {
  const [tableData, setTableData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [modalVisible, setModalVisible] = useState(false);
  const [modalType, setModalType] = useState('add');
  const [form] = Form.useForm();
  const [filters, setFilters] = useState({ vendor: null, status: null });
  const [selectedVendor, setSelectedVendor] = useState(null);

  useEffect(() => {
    fetchData();
  }, [filters]);

  const fetchData = async () => {
    setLoading(true);
    try {
      const response = await modelApi.list({
        vendor: filters.vendor,
        status: filters.status
      });
      if (response.code === 200) {
        setTableData(response.data || []);
      }
    } catch (error) {
      message.error('获取模型列表失败');
    } finally {
      setLoading(false);
    }
  };

  const getVendorName = (vendor) => {
    return vendorOptions.find(v => v.value === vendor)?.label || vendor;
  };

  // 厂商选择变化时自动填充默认 API Base
  const handleVendorChange = (vendor) => {
    setSelectedVendor(vendor);
    const config = VENDOR_CONFIGS[vendor];
    
    if (config && modalType === 'add') {
      // 自动填充 API Base 和默认模型
      form.setFieldsValue({
        api_base: config.apiBase,
        model_name: config.models[0]
      });
    }
  };

  const handleAdd = () => {
    setModalType('add');
    setSelectedVendor(null);
    form.resetFields();
    setModalVisible(true);
  };

  const handleEdit = (record) => {
    setModalType('edit');
    setSelectedVendor(record.vendor);
    form.setFieldsValue(record);
    setModalVisible(true);
  };

  const handleDelete = async (id) => {
    try {
      await modelApi.delete(id);
      message.success('删除成功');
      fetchData();
    } catch (error) {
      message.error('删除失败');
    }
  };

  const handleTest = async (id) => {
    try {
      const response = await modelApi.test(id);
      message.success(response.msg || '连通测试成功');
    } catch (error) {
      message.error('连通测试失败');
    }
  };

  const handleStatusChange = async (record) => {
    try {
      if (record.status === 1) {
        await modelApi.disable(record.id);
      } else {
        await modelApi.enable(record.id);
      }
      message.success('状态更新成功');
      fetchData();
    } catch (error) {
      message.error('状态更新失败');
    }
  };

  const handleSave = async () => {
    try {
      const values = await form.validateFields();
      if (modalType === 'add') {
        await modelApi.add(values);
        message.success('添加成功');
      } else {
        await modelApi.update(values.id, values);
        message.success('更新成功');
      }
      setModalVisible(false);
      fetchData();
    } catch (error) {
      console.error('保存失败:', error);
    }
  };

  const columns = [
    {
      title: '厂商',
      dataIndex: 'vendor',
      render: (vendor) => <Tag>{getVendorName(vendor)}</Tag>
    },
    {
      title: '模型名称',
      dataIndex: 'model_name'
    },
    {
      title: 'API Base',
      dataIndex: 'api_base',
      ellipsis: true
    },
    {
      title: '状态',
      dataIndex: 'status',
      render: (status, record) => (
        <Switch
          checked={status === 1}
          onChange={() => handleStatusChange(record)}
          checkedChildren="启用"
          unCheckedChildren="禁用"
        />
      )
    },
    {
      title: '连通性',
      dataIndex: 'connect_status',
      render: (status) => (
        status === 1 ?
          <CheckCircleFilled style={{ color: '#67C23A', fontSize: 18 }} /> :
          <CloseCircleFilled style={{ color: '#F56C6C', fontSize: 18 }} />
      )
    },
    {
      title: '优先级',
      dataIndex: 'priority'
    },
    {
      title: '操作',
      render: (_, record) => (
        <Space>
          <Tooltip title="测试连通">
            <Button
              type="text"
              icon={<ApiOutlined />}
              onClick={() => handleTest(record.id)}
            />
          </Tooltip>
          <Tooltip title="编辑">
            <Button
              type="text"
              icon={<EditOutlined />}
              onClick={() => handleEdit(record)}
            />
          </Tooltip>
          <Popconfirm
            title="确定删除此模型?"
            onConfirm={() => handleDelete(record.id)}
          >
            <Tooltip title="删除">
              <Button type="text" danger icon={<DeleteOutlined />} />
            </Tooltip>
          </Popconfirm>
        </Space>
      )
    }
  ];

  // 检查是否为本地模型（不需要 API Key）
  const isLocalModel = selectedVendor && VENDOR_CONFIGS[selectedVendor]?.needApiKey === false;

  return (
    <div>
      <Card className="filter-card">
        <Space>
          <Select
            placeholder="全部厂商"
            allowClear
            style={{ width: 150 }}
            options={vendorOptions}
            value={filters.vendor}
            onChange={(value) => setFilters({ ...filters, vendor: value })}
          />
          <Select
            placeholder="全部状态"
            allowClear
            style={{ width: 120 }}
            options={[
              { label: '启用', value: 1 },
              { label: '禁用', value: 0 }
            ]}
            value={filters.status}
            onChange={(value) => setFilters({ ...filters, status: value })}
          />
          <Button type="primary" icon={<SearchOutlined />} onClick={fetchData}>
            刷新
          </Button>
        </Space>
      </Card>

      <Card
        title="模型配置列表"
        extra={
          <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
            添加模型
          </Button>
        }
        className="table-card"
      >
        <Table
          dataSource={tableData}
          columns={columns}
          rowKey="id"
          loading={loading}
          pagination={{ pageSize: 10 }}
        />
      </Card>

      <Modal
        title={modalType === 'add' ? '添加模型' : '编辑模型'}
        open={modalVisible}
        onOk={handleSave}
        onCancel={() => setModalVisible(false)}
        width={650}
      >
        <Form form={form} layout="vertical">
          <Form.Item name="id" hidden>
            <Input />
          </Form.Item>
          
          <Form.Item
            name="vendor"
            label="厂商"
            rules={[{ required: true, message: '请选择厂商' }]}
          >
            <Select 
              options={vendorOptions} 
              placeholder="请选择厂商"
              onChange={handleVendorChange}
            />
          </Form.Item>
          
          <Form.Item
            name="model_name"
            label="模型名称"
            rules={[{ required: true, message: '请输入模型名称' }]}
          >
            <Input placeholder="请输入模型名称" />
          </Form.Item>
          
          <Form.Item
            name="api_base"
            label="API Base"
            tooltip={selectedVendor ? `默认值: ${VENDOR_CONFIGS[selectedVendor]?.apiBase || ''}` : ''}
            rules={[{ required: true, message: '请输入 API Base 地址' }]}
          >
            <Input placeholder={selectedVendor ? VENDOR_CONFIGS[selectedVendor]?.apiBase : 'https://api.example.com/v1'} />
          </Form.Item>
          
          <Form.Item
            name="api_key"
            label="API Key"
            tooltip={isLocalModel ? '本地模型通常不需要 API Key' : '请输入对应的 API Key'}
            rules={[
              { 
                required: !isLocalModel, 
                message: isLocalModel ? '本地模型可留空' : '请输入 API Key' 
              }
            ]}
          >
            <Input.Password 
              placeholder={isLocalModel ? '本地模型可留空' : '请输入 API Key'} 
            />
          </Form.Item>
          
          <Form.Item name="priority" label="优先级" initialValue={100}>
            <InputNumber min={1} max={999} style={{ width: '100%' }} />
            <span className="form-tip" style={{ marginLeft: 8, color: '#999' }}>
              数字越小优先级越高
            </span>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default ModelConfig;
