// frontend-react/src/pages/QuotaMonitor.jsx
import React, { useState, useEffect } from 'react';
import { Card, Table, Tag, Button, Progress, Space, Statistic, Row, Col, Modal, Form, InputNumber, message, DatePicker, List } from 'antd';
import { SyncOutlined, EditOutlined, ReloadOutlined } from '@ant-design/icons';
import ReactECharts from 'echarts-for-react';
import { quotaApi, configApi, statsApi } from '../services/api';
import dayjs from 'dayjs';

const { RangePicker } = DatePicker;

const QuotaMonitor = () => {
  const [quotaList, setQuotaList] = useState([]);
  const [historyData, setHistoryData] = useState([]);
  const [usageTrend, setUsageTrend] = useState([]);
  const [modelRanking, setModelRanking] = useState([]);
  const [switchThreshold, setSwitchThreshold] = useState(99);
  const [editModalVisible, setEditModalVisible] = useState(false);
  const [editForm] = Form.useForm();
  const [editingRow, setEditingRow] = useState(null);
  const [loading, setLoading] = useState(false);
  const [dateRange, setDateRange] = useState([dayjs().subtract(30, 'days'), dayjs()]);

  useEffect(() => {
    fetchQuotaData();
    fetchHistoryData();
    fetchUsageTrend();
    fetchModelRanking();
    fetchSwitchThreshold();
  }, [dateRange]);

  const fetchQuotaData = async () => {
    try {
      const response = await statsApi.quota();
      if (response.code === 200) {
        setQuotaList(response.data?.models || []);
      }
    } catch (error) {
      console.error('获取额度数据失败:', error);
    }
  };

  const fetchHistoryData = async () => {
    try {
      const response = await quotaApi.history({ days: 30 });
      if (response.code === 200) {
        setHistoryData(response.data || []);
      }
    } catch (error) {
      console.error('获取历史数据失败:', error);
    }
  };

  const fetchUsageTrend = async () => {
    try {
      const [start, end] = dateRange;
      const days = end.diff(start, 'day') + 1;
      const response = await statsApi.trends({ days });
      if (response.code === 200) {
        setUsageTrend(response.data?.trend || []);
      }
    } catch (error) {
      console.error('获取使用趋势失败:', error);
    }
  };

  const fetchModelRanking = async () => {
    try {
      const response = await statsApi.models();
      if (response.code === 200) {
        setModelRanking(response.data?.rankings || []);
      }
    } catch (error) {
      console.error('获取模型排行失败:', error);
    }
  };

  const fetchSwitchThreshold = async () => {
    try {
      const response = await configApi.get('switch_threshold');
      if (response.code === 200) {
        setSwitchThreshold(parseInt(response.data?.config_value) || 99);
      }
    } catch (error) {
      console.error('获取切换阈值失败:', error);
    }
  };

  const handleSync = async (modelId) => {
    try {
      setLoading(true);
      const response = await quotaApi.sync(modelId);
      if (response.code === 200) {
        message.success('额度同步成功');
        fetchQuotaData();
      } else {
        message.error(response.msg || '额度同步失败');
      }
    } catch (error) {
      message.error('额度同步失败');
    } finally {
      setLoading(false);
    }
  };

  const handleSyncAll = async () => {
    try {
      setLoading(true);
      for (const item of quotaList) {
        await quotaApi.sync(item.model_id);
      }
      message.success('全部额度同步完成');
      fetchQuotaData();
    } catch (error) {
      message.error('同步失败');
    } finally {
      setLoading(false);
    }
  };

  const handleEdit = (record) => {
    setEditingRow(record);
    editForm.setFieldsValue({
      total_quota: record.total,
      used_quota: record.used
    });
    setEditModalVisible(true);
  };

  const handleSave = async () => {
    try {
      const values = await editForm.validateFields();
      await quotaApi.update(editingRow.model_id, values);
      message.success('额度更新成功');
      setEditModalVisible(false);
      fetchQuotaData();
    } catch (error) {
      console.error('更新失败:', error);
    }
  };

  const total = quotaList.reduce((sum, item) => sum + (item.total || 0), 0);
  const used = quotaList.reduce((sum, item) => sum + (item.used || 0), 0);
  const remain = total - used;
  const usageRate = total > 0 ? ((used / total) * 100).toFixed(1) : 0;

  const sufficientCount = quotaList.filter(item => (item.usage_rate || 0) < 70).length;
  const warningCount = quotaList.filter(item => (item.usage_rate || 0) >= 70 && (item.usage_rate || 0) < 90).length;
  const alertCount = quotaList.filter(item => (item.usage_rate || 0) >= 90).length;

  const usageChartOption = {
    tooltip: { trigger: 'axis' },
    grid: { left: 50, right: 20, top: 30, bottom: 30 },
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: (usageTrend || []).map(item => item.date)
    },
    yAxis: { type: 'value', minInterval: 1 },
    series: [
      {
        name: '请求次数',
        type: 'line',
        data: (usageTrend || []).map(item => item.requests),
        itemStyle: { color: '#1890ff' },
        areaStyle: { color: 'rgba(24, 144, 255, 0.2)' }
      }
    ]
  };

  const rankingChartOption = {
    tooltip: { trigger: 'item', formatter: '{b}: {c} ({d}%)' },
    series: [
      {
        name: '模型使用',
        type: 'pie',
        radius: ['45%', '70%'],
        avoidLabelOverlap: false,
        itemStyle: { borderRadius: 6, borderColor: '#fff', borderWidth: 2 },
        label: { show: false },
        emphasis: { label: { show: true, fontSize: 14 } },
        data: (modelRanking || []).slice(0, 5).map(item => ({
          value: item.requests || 0,
          name: item.model || '未知模型'
        }))
      }
    ]
  };

  const statusColors = {
    success: { bg: '#f6ffed', border: '#52c41a', text: '#135200' },
    warning: { bg: '#fffbe6', border: '#faad14', text: '#ad6800' },
    danger: { bg: '#fff2f0', border: '#ff4d4f', text: '#cf1322' }
  };

  const columns = [
    {
      title: '模型',
      key: 'model',
      render: (_, record) => (
        <Space direction="vertical" size={0}>
          <Tag color="blue">{record.vendor}</Tag>
          <span style={{ fontWeight: 500 }}>{record.model_name}</span>
        </Space>
      )
    },
    {
      title: '总额度',
      dataIndex: 'total',
      render: (val) => val >= 1000000 ? `${(val / 1000000).toFixed(2)}M` : val?.toLocaleString() || '0'
    },
    {
      title: '已用额度',
      dataIndex: 'used',
      render: (val) => val >= 1000000 ? `${(val / 1000000).toFixed(2)}M` : val?.toLocaleString() || '0'
    },
    {
      title: '剩余额度',
      dataIndex: 'remain',
      render: (val) => val >= 1000000 ? `${(val / 1000000).toFixed(2)}M` : val?.toLocaleString() || '0'
    },
    {
      title: '使用率',
      dataIndex: 'usage_rate',
      render: (val) => {
        const status = val >= 90 ? 'exception' : val >= 70 ? 'warning' : 'success';
        const color = status === 'exception' ? '#cf1322' : status === 'warning' ? '#d46b08' : '#389e0d';
        return (
          <div style={{ minWidth: 120 }}>
            <Progress
              percent={val}
              size="small"
              status={status}
              strokeColor={color}
              format={(p) => `${p?.toFixed(1)}%`}
            />
          </div>
        );
      }
    },
    {
      title: '同步时间',
      dataIndex: 'last_sync_time',
      render: (val) => val || '未同步'
    },
    {
      title: '操作',
      render: (_, record) => (
        <Space>
          <Button
            type="text"
            icon={<SyncOutlined spin={loading} />}
            onClick={() => handleSync(record.model_id)}
            loading={loading}
          >
            同步
          </Button>
          <Button
            type="text"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record)}
          >
            编辑
          </Button>
        </Space>
      )
    }
  ];

  return (
    <div>
      <Row gutter={[20, 20]} style={{ marginBottom: 20 }}>
        <Col span={6}>
          <Card>
            <Statistic title="总额度" value={total / 1000000} suffix="M Tokens" precision={2} />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <Statistic title="已用额度" value={used / 1000000} suffix="M" precision={2} valueStyle={{ color: '#cf1322' }} />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <Statistic title="剩余额度" value={remain / 1000000} suffix="M" precision={2} valueStyle={{ color: '#389e0d' }} />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <div style={{ marginBottom: 8 }}>总体使用率</div>
            <Progress
              percent={usageRate}
              size="small"
              status={usageRate >= 90 ? 'exception' : usageRate >= 70 ? 'warning' : 'success'}
              strokeColor={usageRate >= 90 ? '#cf1322' : usageRate >= 70 ? '#faad14' : '#52c41a'}
              format={(p) => `${p}%`}
            />
          </Card>
        </Col>
      </Row>

      <Row gutter={[20, 20]} style={{ marginBottom: 20 }}>
        <Col span={16}>
          <Card
            title="📈 使用趋势"
            extra={
              <Space>
                <RangePicker
                  value={dateRange}
                  onChange={(dates) => dates && setDateRange(dates)}
                />
                <Button icon={<ReloadOutlined />} onClick={() => fetchUsageTrend()}>刷新</Button>
              </Space>
            }
          >
            <ReactECharts option={usageChartOption} style={{ height: 280 }} />
          </Card>
        </Col>
        <Col span={8}>
          <Card title="🚨 额度状态分布">
            <div style={{ padding: '10px 0' }}>
              <div style={{
                marginBottom: 16,
                padding: 16,
                borderRadius: 8,
                background: statusColors.success.bg,
                border: `1px solid ${statusColors.success.border}`,
                color: statusColors.success.text
              }}>
                <div style={{ fontSize: 24, fontWeight: 600 }}>{sufficientCount}</div>
                <div>充足 (使用率 &lt; 70%)</div>
              </div>
              <div style={{
                marginBottom: 16,
                padding: 16,
                borderRadius: 8,
                background: statusColors.warning.bg,
                border: `1px solid ${statusColors.warning.border}`,
                color: statusColors.warning.text
              }}>
                <div style={{ fontSize: 24, fontWeight: 600 }}>{warningCount}</div>
                <div>预警 (70% ≤ 使用率 &lt; 90%)</div>
              </div>
              <div style={{
                padding: 16,
                borderRadius: 8,
                background: statusColors.danger.bg,
                border: `1px solid ${statusColors.danger.border}`,
                color: statusColors.danger.text
              }}>
                <div style={{ fontSize: 24, fontWeight: 600 }}>{alertCount}</div>
                <div>告警 (使用率 ≥ 90%)</div>
              </div>
            </div>
          </Card>
        </Col>
      </Row>

      <Row gutter={[20, 20]} style={{ marginBottom: 20 }}>
        <Col span={12}>
          <Card title="🏆 模型使用排行 (Top 5)">
            <List
              size="small"
              dataSource={modelRanking.slice(0, 5)}
              renderItem={(item, index) => (
                <List.Item>
                  <Space style={{ width: '100%', justifyContent: 'space-between' }}>
                    <Space>
                      <Tag color={index === 0 ? 'gold' : index === 1 ? 'silver' : index === 2 ? 'bronze' : 'default'}>{index + 1}</Tag>
                      <span>{item.model}</span>
                    </Space>
                    <Space>
                      <span style={{ color: '#1890ff' }}>{item.requests?.toLocaleString()}</span>
                      <span style={{ color: '#999' }}>({item.percentage}%)</span>
                    </Space>
                  </Space>
                </List.Item>
              )}
            />
          </Card>
        </Col>
        <Col span={12}>
          <Card title="📊 模型使用占比">
            <ReactECharts option={rankingChartOption} style={{ height: 250 }} />
          </Card>
        </Col>
      </Row>

      <Card
        title="📋 模型额度列表"
        extra={
          <Button type="primary" icon={<SyncOutlined />} onClick={handleSyncAll} loading={loading}>
            全部同步
          </Button>
        }
      >
        <Table
          dataSource={quotaList}
          columns={columns}
          rowKey="model_id"
          pagination={{ pageSize: 10 }}
          loading={loading}
        />
      </Card>

      <Modal
        title="编辑额度"
        open={editModalVisible}
        onOk={handleSave}
        onCancel={() => setEditModalVisible(false)}
      >
        <Form form={editForm} layout="vertical">
          <Form.Item name="total_quota" label="总额度 (Tokens)">
            <InputNumber min={0} style={{ width: '100%' }} placeholder="请输入总额度" />
          </Form.Item>
          <Form.Item name="used_quota" label="已用额度 (Tokens)">
            <InputNumber min={0} style={{ width: '100%' }} placeholder="请输入已用额度" />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default QuotaMonitor;

// frontend/src/views/QuotaMonitor.vue
<template>
  <div class="quota-monitor">
    <!-- 统计概览 -->
    <el-row :gutter="20" class="stat-row">
      <el-col :span="6">
        <el-card class="stat-card">
          <div class="stat-content">
            <div class="stat-value">{{ totalQuota }}</div>
            <div class="stat-label">总剩余额度 (Tokens)</div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="stat-card">
          <div class="stat-content">
            <div class="stat-value">{{ totalUsed }}</div>
            <div class="stat-label">已用额度 (Tokens)</div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="stat-card">
          <div class="stat-content">
            <div class="stat-value">{{ avgUsage }}%</div>
            <div class="stat-label">平均使用率</div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="stat-card">
          <div class="stat-content">
            <div class="stat-value">{{ alertCount }}</div>
            <div class="stat-label">告警模型数</div>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <!-- 切换规则配置 -->
    <el-card class="config-card">
      <template #header>
        <div class="card-header">
          <span>自动切换规则</span>
          <el-button type="primary" @click="handleSaveConfig" :loading="saving">
            保存配置
          </el-button>
        </div>
      </template>
      
      <el-form :model="switchConfig" label-width="160px">
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="全局切换阈值">
              <el-slider 
                v-model="switchConfig.threshold" 
                :min="50" 
                :max="100"
                :step="1"
                :format-tooltip="(val) => val + '%'"
              />
              <span class="form-tip">当模型额度消耗超过此阈值时自动切换</span>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="切换策略">
              <el-radio-group v-model="switchConfig.strategy">
                <el-radio label="priority">按优先级切换</el-radio>
                <el-radio label="quota">按剩余额度切换</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
        </el-row>
        
        <el-form-item label="兜底策略">
          <el-checkbox v-model="switchConfig.disableOnEmpty">
            所有模型额度耗尽时禁用网关服务
          </el-checkbox>
        </el-form-item>
        
        <el-form-item label="监控间隔">
          <el-input-number 
            v-model="switchConfig.interval" 
            :min="5" 
            :max="300"
          />
          <span class="form-unit">秒</span>
        </el-form-item>
      </el-form>
    </el-card>

    <!-- 模型额度列表 -->
    <el-card class="table-card">
      <template #header>
        <div class="card-header">
          <span>模型额度详情</span>
          <div class="header-actions">
            <el-button @click="handleSyncAll">
              <el-icon><Refresh /></el-icon>
              同步全部额度
            </el-button>
          </div>
        </div>
      </template>
      
      <el-table :data="quotaList" v-loading="loading" stripe>
        <el-table-column prop="vendor" label="厂商" width="120">
          <template #default="{ row }">
            <el-tag>{{ getVendorName(row.vendor) }}</el-tag>
          </template>
        </el-table-column>
        
        <el-table-column prop="model_name" label="模型" min-width="150" />
        
        <el-table-column label="总额度" width="150">
          <template #default="{ row }">
            {{ formatQuota(row.total_quota) }}
          </template>
        </el-table-column>
        
        <el-table-column label="已用额度" width="150">
          <template #default="{ row }">
            {{ formatQuota(row.used_quota) }}
          </template>
        </el-table-column>
        
        <el-table-column label="剩余额度" width="150">
          <template #default="{ row }">
            {{ formatQuota(row.remain_quota) }}
          </template>
        </el-table-column>
        
        <el-table-column label="使用率" width="200">
          <template #default="{ row }">
            <el-progress 
              :percentage="Math.round(row.used_ratio)" 
              :stroke-width="8"
              :status="getProgressStatus(row.used_ratio)"
              :show-text="false"
            />
            <span class="usage-text">{{ row.used_ratio.toFixed(1) }}%</span>
          </template>
        </el-table-column>
        
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="getQuotaTagType(row.quota_status)" size="small">
              {{ getQuotaStatus(row.quota_status) }}
            </el-tag>
          </template>
        </el-table-column>
        
        <el-table-column label="操作" width="150">
          <template #default="{ row }">
            <el-button-group>
              <el-tooltip content="同步额度">
                <el-button size="small" @click="handleSync(row)">
                  <el-icon><Refresh /></el-icon>
                </el-button>
              </el-tooltip>
              <el-tooltip content="手动录入">
                <el-button size="small" @click="handleManualUpdate(row)">
                  <el-icon><Edit /></el-icon>
                </el-button>
              </el-tooltip>
            </el-button-group>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 额度使用图表 -->
    <el-row :gutter="20" class="chart-row">
      <el-col :span="12">
        <el-card class="chart-card">
          <template #header>
            <span>额度使用占比</span>
          </template>
          <v-chart class="chart" :option="pieOption" autoresize />
        </el-card>
      </el-col>
      <el-col :span="12">
        <el-card class="chart-card">
          <template #header>
            <span>近7天使用趋势</span>
          </template>
          <v-chart class="chart" :option="lineOption" autoresize />
        </el-card>
      </el-col>
    </el-row>

    <!-- 手动录入对话框 -->
    <el-dialog
      v-model="manualDialogVisible"
      title="手动录入额度"
      width="400px"
    >
      <el-form :model="manualForm" label-width="100px">
        <el-form-item label="模型">
          <el-input :value="manualForm.model_name" disabled />
        </el-form-item>
        <el-form-item label="总额度">
          <el-input-number 
            v-model="manualForm.total_quota" 
            :min="0"
            :precision="0"
            style="width: 100%"
          />
        </el-form-item>
        <el-form-item label="已用额度">
          <el-input-number 
            v-model="manualForm.used_quota" 
            :min="0"
            :precision="0"
            style="width: 100%"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="manualDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleManualSave">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, computed, onMounted } from 'vue'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { PieChart, LineChart } from 'echarts/charts'
import { GridComponent, TooltipComponent, LegendComponent } from 'echarts/components'
import VChart from 'vue-echarts'
import { ElMessage } from 'element-plus'
import { Refresh, Edit } from '@element-plus/icons-vue'
import { quotaApi, configApi } from '@/api'

use([CanvasRenderer, PieChart, LineChart, GridComponent, TooltipComponent, LegendComponent])

const loading = ref(false)
const saving = ref(false)
const quotaList = ref([])
const manualDialogVisible = ref(false)

const switchConfig = reactive({
  threshold: 99,
  strategy: 'priority',
  disableOnEmpty: false,
  interval: 10
})

const manualForm = reactive({
  model_id: null,
  model_name: '',
  total_quota: 0,
  used_quota: 0
})

// 计算属性
const totalQuota = computed(() => {
  return quotaList.value.reduce((sum, item) => sum + (item.total_quota || 0), 0)
})

const totalUsed = computed(() => {
  return quotaList.value.reduce((sum, item) => sum + (item.used_quota || 0), 0)
})

const avgUsage = computed(() => {
  if (quotaList.value.length === 0) return 0
  const total = quotaList.value.reduce((sum, item) => sum + (item.used_ratio || 0), 0)
  return (total / quotaList.value.length).toFixed(1)
})

const alertCount = computed(() => {
  return quotaList.value.filter(item => item.quota_status === 1).length
})

// 图表配置
const pieOption = computed(() => ({
  tooltip: { trigger: 'item', formatter: '{b}: {c} ({d}%)' },
  legend: { orient: 'vertical', left: 'left' },
  series: [{
    type: 'pie',
    radius: ['40%', '70%'],
    data: quotaList.value.map(item => ({
      name: item.model_name,
      value: item.used_quota
    }))
  }]
}))

const lineOption = computed(() => ({
  tooltip: { trigger: 'axis' },
  legend: { data: ['使用量'] },
  grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true },
  xAxis: {
    type: 'category',
    boundaryGap: false,
    data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
  },
  yAxis: { type: 'value' },
  series: [{
    name: '使用量',
    type: 'line',
    smooth: true,
    data: [120, 132, 101, 134, 90, 230, 210],
    areaStyle: { opacity: 0.1 }
  }]
}))

// 厂商名称映射
const vendorNameMap = {
  openai: 'OpenAI',
  qwen: '通义千问',
  zhipu: '智谱清言',
  spark: '讯飞星火',
  doubao: '字节豆包',
  claude: 'Claude',
  gemini: 'Google Gemini',
  mistral: 'Mistral',
  groq: 'Groq'
}

const getVendorName = (vendor) => vendorNameMap[vendor] || vendor

const formatQuota = (quota) => {
  if (!quota) return '0'
  if (quota >= 1000000) return `${(quota / 1000000).toFixed(1)}M`
  if (quota >= 1000) return `${(quota / 1000).toFixed(1)}K`
  return quota.toString()
}

const getQuotaStatus = (status) => {
  const map = { 0: '已耗尽', 1: '即将耗尽', 2: '充足' }
  return map[status] || '未知'
}

const getQuotaTagType = (status) => {
  const map = { 0: 'danger', 1: 'warning', 2: 'success' }
  return map[status] || 'info'
}

const getProgressStatus = (ratio) => {
  if (ratio >= 90) return 'exception'
  if (ratio >= 70) return 'warning'
  return 'success'
}

const fetchQuotaData = async () => {
  loading.value = true
  try {
    const res = await quotaApi.stat()
    quotaList.value = res.data || []
  } catch (error) {
    ElMessage.error('获取额度数据失败')
  } finally {
    loading.value = false
  }
}

const fetchSwitchConfig = async () => {
  try {
    const res = await configApi.get('switch_threshold')
    if (res.data) {
      switchConfig.threshold = parseInt(res.data.config_value) || 99
    }
  } catch (error) {
    console.error('获取切换配置失败')
  }
}

const handleSync = async (row) => {
  try {
    await quotaApi.sync(row.model_id)
    ElMessage.success('额度同步成功')
    fetchQuotaData()
  } catch (error) {
    ElMessage.error('额度同步失败')
  }
}

const handleSyncAll = async () => {
  for (const item of quotaList.value) {
    try {
      await quotaApi.sync(item.model_id)
    } catch (error) {
      console.error(`模型 ${item.model_name} 同步失败`)
    }
  }
  ElMessage.success('全部同步完成')
  fetchQuotaData()
}

const handleManualUpdate = (row) => {
  manualForm.model_id = row.model_id
  manualForm.model_name = row.model_name
  manualForm.total_quota = row.total_quota
  manualForm.used_quota = row.used_quota
  manualDialogVisible.value = true
}

const handleManualSave = async () => {
  try {
    await quotaApi.update(manualForm.model_id, {
      total_quota: manualForm.total_quota,
      used_quota: manualForm.used_quota
    })
    ElMessage.success('保存成功')
    manualDialogVisible.value = false
    fetchQuotaData()
  } catch (error) {
    ElMessage.error('保存失败')
  }
}

const handleSaveConfig = async () => {
  saving.value = true
  try {
    await configApi.set({
      key: 'switch_threshold',
      value: switchConfig.threshold.toString()
    })
    ElMessage.success('配置保存成功')
  } catch (error) {
    ElMessage.error('配置保存失败')
  } finally {
    saving.value = false
  }
}

onMounted(() => {
  fetchQuotaData()
  fetchSwitchConfig()
})
</script>

<style lang="scss" scoped>
.quota-monitor {
  .stat-row {
    margin-bottom: 20px;
    
    .stat-card {
      .stat-content {
        text-align: center;
        
        .stat-value {
          font-size: 28px;
          font-weight: bold;
          color: #303133;
        }
        
        .stat-label {
          font-size: 14px;
          color: #909399;
          margin-top: 8px;
        }
      }
    }
  }
  
  .config-card {
    margin-bottom: 20px;
    
    .card-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
  }
  
  .table-card {
    margin-bottom: 20px;
    
    .card-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    
    .usage-text {
      margin-left: 8px;
      font-size: 12px;
      color: #606266;
    }
  }
  
  .chart-row {
    .chart-card {
      .chart {
        height: 300px;
      }
    }
  }
  
  .form-tip, .form-unit {
    margin-left: 8px;
    font-size: 12px;
    color: #909399;
  }
}
</style>
